import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
    const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

    return (
        <>
            <Head>
                <title>BirdSuit</title>
                <meta
                    name="description"
                    content="Generated by CT3 and FlySuit"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <h1>Hello World</h1>
            </div>
        </>
    );
};

export default Home;
